version: 2.1

orbs:
  meliuz: meliuz/services-orb@1.15.0

workflows:
  meliuz-workflow:
    jobs:
      - meliuz/promotes-image:
          context: global
          filters:
            branches:
              only:
                - staging
                - master

      - meliuz/provision-infra-compose:
          context: global
          executor-version: v3.10-1.1.8-alpha.2
          requires:
            - meliuz/promotes-image



