apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: adilson-example
spec:
  generators:
  - git:
      repoURL: https://github.com/adilson-cruz/test-app.git
      revision: HEAD
      files:
      - path: "examples/**.yaml"
  template:
    metadata:
      name: '{{name}}-example'
    spec:
      project: default
      source:
        helm:
          # valueFiles:
          # - values.yaml
          values: |-
            {{values}}
        repoURL: https://github.com/bitnami/charts.git
        targetRevision: HEAD
        path: "bitnami/nginx"
      destination:
        server: '{{address}}'
        namespace: default  